# Generated by Django 4.0.1 on 2023-02-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='active',
        ),
    ]
