# Generated by Django 4.0.1 on 2023-01-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
    ]
