# Generated by Django 4.0.1 on 2023-02-09 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_banner_banner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_type',
        ),
        migrations.AddField(
            model_name='banner',
            name='discount_1',
            field=models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='banner',
            name='discount_2',
            field=models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
