# Generated by Django 4.0.1 on 2023-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_useraddressbook_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressbook',
            name='address_name',
            field=models.CharField(default='Home', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='town_or_city',
            field=models.CharField(max_length=1000),
        ),
    ]
