# Generated by Django 4.0.1 on 2023-02-26 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_banner_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='shop/product_images')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productattribute')),
            ],
        ),
    ]
