# Generated by Django 4.0.1 on 2023-03-03 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_images_productattributepictures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.productattributepictures'),
        ),
    ]
