# Generated by Django 4.0.1 on 2023-03-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_productattribute_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPicture',
        ),
    ]
